sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run test
node_js:
  - '9'
  - '8'
after_success:
  - npm run semantic-release
